#Pirkko Suihkonen, May 31, 2017
#
INF: ^(to (associate|abase|abhor|abide|abode|abolish|abound|abstain|abuse|
  accept|access|accompany|accomplish|account|accurse|accuse|accustom|
  acknowledge|acquaint|acquit|act|add|addict|adjure|administer|admire|
  admonish|adorn|advance|advantage|adventure|advertise|advise|advocate|
  affect|affection|affirm|afflict|afford|affright|age|agree|aid|ail|alarm|
  alienate|allege|ally|allow|allure|alter|amaze|ambassage|ambus|amend|amerce|
  amount|anger|anoint|answer|apparel|appeal|appear|appease|appertain|apply|
  appoint|apprehend|approach|approve|argue|arise|arm|armour|arise|array|
  ascend|ascribe|ashame|ashtore|ask|assault|assay|assemble|assent|assign|
  assist|assure|asswage|astonish|astray|attain|attend|attire|avail|avenge|
  avoid|avouch|await|awake|babbl|backbite|bade|bake|band|banish|banquet|
  baptize|bark|bathe|battere|be|bear|beat|beautify|become|beckone|befall|
  beg|begin|beget|beg|beguile|behave|behead|behold|behove|belie|believe|
  belong|belove|bemoan|bend|benefit|bereave|beseech|beset|bestead|bet|
  bethink|betray|betroth|better|bewail|beware|bewitch|bewray|bid|bind|
  bite|blame|blaspheme|blast|blaze|bleat|blemish|bless|blow|blind|blindfold|
  bloom|blossom|blot|blunt|blush|boast|boil|bolt|bond|bore|bear|borrow|buy|
  bow|brake|braw|bray|break|breathe|breed|bribe|bridle|bring|broid|broil|
  bruise|bruit|bud|buffet|build|bull|bundle|burden|bury|burn|burnish|burst|
  busy|cag|call|calm|calve|camp|can|cane|canker|care|carry|cart|carve|case|
  cast|catch|cause|cave|cease|celebrate|certify|chafe|chaff|challenge|chamber|
  champion|chance|change|chant|charge|charm|chase|chasten|chastise|chatter|
  cheek|cheer|cherish|chew|chide|choke|choose|chop|churn|ciel|circuit|
  circumcise|clap|clean|cleanse|clear|cleave|climb|clip|close|clothe|cloute|
  coffin|collar|colour|come|comfort|command|commend|commit|commune|communicate|
  compact|company|compare|compass|compel|complain|complete|compound|
  comprehend|conceal|conveive|concern|conclude|condemn|condescend|conduct|
  confederate|confer|confess|confirm|conflict|conform|confound|confuse|
  congealed|congratulate|conquer|consecrate|consent|consider|consort|conspire|
  constrain|consult|consume|contain|contemn|contend|continue|contradict|
  convert|convay|convict|convince|cook|cool|copy|cord|corner|correct|corrupt|
  cost|couch|counsel|count|countervail|couple|course|court|covenant|cover|
  covet|crackle|craft|crane|chrash|crave|create|creep|crib|cry|cripple|crisp|
  crook|crop|cross|crouch|crow|crown|crucify|crush|cuckow|cumber|cup|curdle|
  cure|curse|curtain|cut|dam|damage|damn|dance|dandle|dare|darken|dart|dash|
  daub|deal|debase|decay|decease|deceive|decide|deck|declare|decline|decrease|
  decree|dedicate|deem|defame|defeat|defence|defend|defer|defy|defile|defraud|
  degenerate|delay|delight|deliver|demand|deny|depart|depose|deprive|depute|
  deride|descend|describe|descry|desert|deserve|desire|desolate|despair|
  despise|desdroy|detain|determine|detest|devise|devote|devour|dial|do|die|
  differ|differ|dig|dim|diminish|dine|dip|direct|disallow|disannul|disappoint|
  discern|discharge|discipline|disclose|discomfit|discontent|discontinue|
  discourage|discover|disdain|disease|disfigure|disgrace|disguise|dish|
  dishonour|disinherit|dismay|dismiss|disobey|disperse|display|displease|
  displeasure|dispose|dispossess|dispute|disquiet|dissemble|dissolve|distil|
  distract|distress|distribute|divide|divine|divorce|dot|double|doubt|drag|
  draw|dread|dream|dress|drive|drop|drown|drink|dry|dull|dumb|dung|dure|dwarf|
  dwell|dye|ear|earn|earth|ease|eat|edify|endeavour|exalt|effect|elect|embalm|
  embolden|embrace|employ|empty|enable|encounter|encourage|endamage|endanger|
  endeavour|end|endow|enduce|endure|enflame|engage|engraft|engrave|enjoin|
  enlarge|enlighten|enquire|enrich|ensnare|ensue|engtangle|enter|entertain|
  entice|entreat|envy|erect|err|escape|eschew|espy|espouse|establish|esteem|
  estimate|estrange|exact|exalted|examine|exceed|excel|except|excess|exchange|
  exclude|excuse|execute|exempt|exercise|exhort|exile|expect|expel|expire|
  expound|express|extend|extinct|extol|eye|fade|fail|faint|fair|fall|falsify|
  famish|fan|fare|farm|fashion|fast|fasten|fat|fault|favour|fear|feast|
  feather|feed|feel|feign|fence|ferret|fetch|fetch|fight|figure|file|fill|
  find|finger|fine|finish|fire|fish|fit|fix|flag|flame|flash|flatter|flay|
  flee|fleece|flesh|fly|flight|flock|flood|floor|flour|flourish|flow|flutter|
  foam|fold|follow|fool|foot|forbear|forbid|force|ford|forecast|foreknow|
  foreordain|foresee|forest|foretell|forewarn|forfeit|forget|forgive|forge|
  form|forsake|forswear|fortify|foul|frame|fray|freckle|free|frequent|fret|
  fry|fringe|front|frost|freeze|fruit|frustrate|fulfil|furbish|furnish|
  further|gad|gain|gainsay|gall|gap|garden|garnish|gate|gather|give|gaze|
  gender|get|ghost|gird|girdle|gird|glass|glean|glister|glitter|glory|
  glorify|gnash|gnaw|go|goad|gore|govern|grace|graff|grain|grant|grate|grave|
  gravel|gray|grease|green|greet|grow|grey|grieve|grind|grisle|groan|grope|
  gross|ground|grudge|guard|guide|gush|gutter|have|hail|hallow|halt|hand|
  handle|hang|happen|harden|hare|harness|harp|harrow|harvest|haste|hasten|
  hatch|hate|haunt|hawk|hazard|heal|heap|hear|hearken|heat|heave|hedge|heed|
  heel|hold|help|hew|hid|hide|hinder|hire|hiss|hit|hoise|hole|hollow|honour|
  hook|hope|horse|host|hough|house|howl|humble|hunger|hunt|hurl|hurt|husk|
  idle|illuminate|image|imagine|impart|impose|impoverish|imprison|impute|
  incense|incline|inclose|increase|increase|indebt|indite|inflame|inflict|
  infold|inform|ingather|inhabit|inherit|injure|instruct|intend|intent|
  intermeddle|interpret|intreat|intrude|invade|invent|invite|issue|itch|
  jangle|jaw|jeoparde|jest|join|joint|jot|journey|joy|judge|jump|justify|
  justle|keep|kick|kill|kindle|kiss|kite|knead|kneel|know|knit|knock|labour|
  lack|lade|lay|lie|lame|lament|lance|land|languish|lap|last|latch|lattice|
  laugh|lavish|lead|league|lean|leap|learn|lease|leave|lend|lengthen|let|
  levy|lick|lift|lighten|like|lime|limit|linger|lip|list|live|load|loan|
  loathe|lock|lodge|loft|long|look|loose|lop|lose|lot|lothe|love|lower|lump|
  lurk|lust|make|magnify|mail|maim|maintain|manifest|mar|marble|mark|market|
  mar|marry|marvel|mate|may|mean|measure|meddle|meditate|meet|melt|mend|
  mention|merchandise|mete|might|mildew|mince|mind|mingle|minish|minister|
  mire|miscarry|miss|mist|misuse|mix|mock|moisten|mollify|morning|mortar|
  mortify|mount|mourn|mouse|move|mown|multiply|murmur|muse|must|muster|
  mutter|muzzle|nail|nake|name|narrow|near|need|needle|neglect|neigh|nest|
  noise|nose|note|notice|nourish|number|nurse|object|obscure|observe|obtain|
  obtainy|offend|offer|oil|omit|open|oppose|oppress|ordain|order|ought|
  outcast|outlive|outrun|outstretch|outgo|overcome|overcharge|overflow|
  overlay|overlive|overpass|overrun|oversee|overshadow|overspread|overtake|
  overthrew|overturn|overwhelm|owe|own|paddle|pay|pain|paint|pair|pan|pant|
  parch|pardon|pare|part|pass|pasture|pattern|pave|paw|pearl|peel|
  peep|perceive|perfect|perform|perfume|peril|perish|perjure|permit|perplex|
  persecute|persuade|persude|pertain|pervert|pestle|pierce|pill|pin|pinnacle|
  pipe|piss|pitch|pity|place|plague|plaister|plait|plant|plate|play|plead|
  please|pledge|plot|plow|pluck|pluck|plunge|point|pole|polish|poll|pollute|
  ponder|pool|port|possess|potter|pour|pourtray|power|practise|praise|pranse|
  prate|pray|preach|predestinate|prefer|premeditate|prepare|prescribe|preent|
  prserve|press|presume|prevail|prevent|prey|prick|pride|print|prise|prize|
  proceed|process|proclaim|procure|produce|profane|profess|profit|prolong|
  promise|promote|pronounce|proof|prophesy|proselyte|prospect|protest|prove|
  provide|prove|provoke|prune|publish|pudd|pull|pulse|punish|purchase|purge|
  purify|purloin|purpose|pursue|push|put|putrify|quake|quarrel|quench|
  question|quicken|quiet|quit|quiver|rage|rag|rail|rain|raise|rampar|run|
  ring|rank|ransom|rase|rate|rattle|raven|ravish|reach|read|reap|rear|reason|
  rebel|rebuke|recall|receipt|receive|reckon|recommend|recompense|reconcile|
  reorder|recount|recover|redeem|redound|reel|refine|reform|refrain|refresh|
  refuge|refuse|regard|rehearse|reign|reject|rejoice|release|rely|relieve|
  remain|remember|remit|remove|rend|render|renew|renounce|rent|repair|repay|
  repeat|repent|replenish|reply|report|reproach|reproof|repute|request|
  require|requite|reward|rescue|resemble|reserve|resist|resolve|resort|
  respect|rest|restore|restain|retain|retire|return|reveal|revenge|reverence|
  reverse|revile|revive|revolt|reward|rid|riddle|ride|rifle|right|ring|rinse|
  riot|rip|rise|roar|roast|rob|robe|roll|root|rope|rot|round|rouse|row|rub|
  rubb|rue|ruin|rule|rumble|rumour|run|rush|sacrifice|sacrify|saddle|say|sail|
  saint|salt|salute|sanctify|sing|sink|sap|sit|satiate|satisfy|save|savour|
  see|say|scab|scalp|scant|scare|scatter|scent|school|scoff|scorch|scorn|
  scour|scrabble|scrape|scribe|scroll|seal|seam|search|sear|season|seat|
  secure|seduce|see|seed|seek|seem|seize|sell|send|sense|separate|serve|
  service|set|settle|sever|sew|shade|shadow|shake|shall|shame|shape|share|
  sharpen|shave|shear|shed|shelter|shew|shine|ship|shock|shoed|shoe|shoot|
  shore|shear|short|shorten|shout|shovel|shrink|shred|shun|shut|shuttle|
  sieve|sift|sigh|sign|signify|silver|sin|sinew|situate|skip|skirt|slack|
  slay|slander|slang|slave|slay|sleep|slew|slide|slime|slip|slow|slumber|
  smart|smell|smite|smoke|smooth|snare|sneeze|snort|snow|snuff|soak|soap|
  sober|sod|soil|sojourn|solace|sop|sorrow|sort|sound|sour|speak|span|spare|
  spark|spat|spear|speckle|speed|spend|spew|spice|spy|spill|spin|spirit|spit|
  spite|spite|spoil|sport|spot|spring|spread|sprinkle|sprout|spue|square|
  stablish|staff|stagger|stain|stalk|stall|stammer|stamp|stanch|stand|stink|
  stare|state|stay|stead|steal|steel|steep|stem|step|steward|stick|stiffen|
  still|sting|stink|stir|stone|stool|stoop|stop|store|storm|strain|straiten|
  strait|straw|stream|strenghen|stretch|stricke|strike|string|stripe|stripe|
  strip|strive|strow|struggle|study|stumble|stump|subdue|subject|submit|
  subscribe|subvert|succeed|succour|suck|suckle|sue|suffer|suffice|suit|sum|
  sun|sunder|sup|supplant|supply|support|suppose|surfeit|surname|surprise|
  sustain|swaddle|swallow|swear|swarm|sweep|swell|swerve|swim|taber|tackle|
  take|talk|tame|tarry|task|tast|teach|taunt|tax|teach|teil|temper|tempt|
  tend|term|terrify|testify|thank|think|thirst|threaten|thresh|throw|throng|
  thrust|thumb|thunder|tie|tile|time|tin|tingle|tinkle|tip|tire|tithe|toil|
  token|toll|tongue|top|torment|torture|toss|totter|touch|tow|towel|trade|
  trade|trane|trample|transfer|transfigure|transform|transgress|translate|
  travail|travel|traverse|tread|treasure|tremble|trespass|trickle|try|trim|
  triumph|troop|trouble|trow|trump|trust|turn|twine|twinkle|uncloth|uncover|
  undergird|understand|undertake|undo|undress|ungeign|ungird|unite|unlade|
  unlearn|unleaven|unloose|unmarry|unoccupy|unperfect|unstop|untemper|upbraid|
  uphold|upris|urge|use|usurp|utter|vagabond|vail|value|vanish|vaunt|veil|
  vent|venture|verify|vesture|vex|view|violate|visit|voice|void|vomit|vow|
  wait|wake|walk|wall|wander|want|ward|ware|warm|warn|ward|war|wash|waste|
  watch|water|water|wave|wax|wayfare|waken|wean|wear|weary|weave|wed|wedge|
  weep|wigh|wend|weep|wert|wet|whet|whirl|whisper|white|whore|will|wilt|win|
  wink|winter|wipe|wise|wish|withdraw|wither|withhold|withstand|witness|
  wonder|wont|work|worm|worship|wot|wound|wrap|wreath|wrest|wrestle|wretch|
  wring|wrinkle|write|wrong|work|wring|yarn|yearn|yell|yellow|yield|yoke))
#
