#! /usr/bin/perl -s

my $vers = '$Id: bible-eng-split,v 1.3 2007/06/16 06:56:44 jtlaakso Exp $';

use diagnostics;
use strict;

use vars qw($help $version $copyright $raw);

my @lines;
my $n = 0;

my @book = (
	    "gn","ex","lv","nu","dt","js","jg","ru","1s","2s",
	    "1k","2k","1x","2x","er","ne","es","jb","ps","pr",
	    "ec","ca","is","jr","lm","ek","da","ho","jl","am",
	    "ob","on","mi","na","ha","zp","hg","zc","ma","mt",
	    "mk","lk","jn","ac","rm","1c","2c","ga","ep","pp",
	    "cl","1q","2q","1t","2t","ti","fm","hb","jm","1p",
	    "2p","1j","2j","3j","jd","rv"
	   );

while (<>) {
  print_lines() if !$raw && /^\"<\*book>\"/;
  print_lines() if  $raw && /^Book \d\d /;

  push @lines, $_;
}

print_lines();

#------------------------------------------------------------------------------

sub print_lines {
  if ($#lines>1) {
    $n++;
    my $out = sprintf("eng-%02d-", $n).$book[$n-1];
    $out .= "-tw" unless $raw;
    print "Writing to <$out>\n";
    open OUT, ">$out";
    print OUT @lines;
    close OUT;
  }
  @lines = ();
}
